<a href="https://colab.research.google.com/github/Hariom-byte/Data-Analytics-Library/blob/main/class4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
arr*5  #Broadcasting

array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
arr[[5,6]]

array([6, 7])

You can do this fancy indexing in 2D Matrix aswell

In [ ]:
matrix =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
matrix[2:,2:]

array([[11, 12],
       [15, 16]])

In [ ]:
matrix = np.arange(1,13).reshape(4,3)
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
matrix[[0,0],[1,2]]    # [[rows],[col]]

array([2, 3])

##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr = np.array([10,2,13,1,42,8,35,34,3,4])
arr[arr >15]

#Replace the elements where values are greater than 15.
#Method ->1
arr[arr >15] = 0
print(arr)

#Method ->2
np.where(arr>15,0,arr) #(condition kya, condition kha per, kis se replace)  jaha 15 se bade h bha ye aayega

[10  2 13  1  0  8  0  0  3  4]


array([10,  2, 13,  1,  0,  8,  0,  0,  3,  4])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
arr = np.array([10,2,13,1,42,8,35,34,3,4])
np.sort(arr)

array([ 1,  2,  3,  4,  8, 10, 13, 34, 35, 42])

In [ ]:
arr = np.array([10,2,13,1,42,8,35,34,3,4])
np.argsort(arr)

array([3, 1, 8, 9, 5, 0, 2, 7, 6, 4])

##Concatenation & Stacking

In [ ]:
import numpy as np
a =np.array([1,2,3,4])
b = np.array([5,6,7])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
matrixA = np.array([[1,2,3],[4,5,6]])
matrixB = np.array([[7,8,9],[1,1,2]])
print(matrixA)
print(matrixB)
np.concatenate([matrixA,matrixB])

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [1 1 2]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 2]])

Vertical & Horizontal Stacking

In [ ]:
matrixA = np.array([[1,2,3],[4,5,6]])
matrixB = np.array([[7,8,9],[1,1,2]])
np.vstack([matrixA,matrixB])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 2]])

In [ ]:
matrixA = np.array([[1,2,3],[4,5,6]])
matrixB = np.array([[7,8,9],[1,1,2]])
np.hstack([matrixA,matrixB])

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 1, 1, 2]])

In [ ]:
#1.shape
#2. size
#3. descriptive statistical functions(mean,std,variance,min,max)
