<a href="https://colab.research.google.com/github/Hariom-byte/Data-Analytics-Library/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
#some basic Arithmetic Operations.
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([7, 8, 9])
print(f"Addition of arr1 and arr2:{arr1+arr2} ")
print(f"Subtraction of arr1 and arr2:{arr1-arr2} ")
print(f"Multiplication of arr1 and arr2:{arr1*arr2} ")
print(f"Division of arr1 and arr2:{arr1/arr2} ")

Addition of arr1 and arr2:[ 8 10 12] 
Subtraction of arr1 and arr2:[-6 -6 -6] 
Multiplication of arr1 and arr2:[ 7 16 27] 
Division of arr1 and arr2:[0.14285714 0.25       0.33333333] 


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
#Array Broadcasting
arr1*5

array([ 5, 10, 15])

Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9],[10,11,13]])
print(f"Addition of arr1 and arr2:{arr1+arr2} ")


Addition of arr1 and arr2:[[ 8 10 12]
 [14 16 19]] 


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
arr = np.array([4,8,15,16,23,42])
print(f"Max of arr:{arr.sum()}")
print(f"Mean of arr:{arr.mean()}")
print(f"Median of arr:{arr.max()}")
print(f"Standard Deviation of arr:{arr.min()}")

Max of arr:108
Mean of arr:18.0
Median of arr:42
Standard Deviation of arr:4


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:

matrix = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(matrix.sum(axis=1)) #axis=1 for rows
print(matrix.sum(axis=0)) #axis=0 for columns

[ 6 15 24]
[12 15 18]


In [ ]:
#sort -> on the elements
arr = np.array([5,6,1,2,0])
print(np.sort(arr))

[0 1 2 5 6]


In [ ]:
#argsort ->if we have to sort index first
index = np.argsort(arr)
print("Indexs:",index)
print("Element after sort",arr[index])


Indexs: [4 2 3 0 1]
Element after sort [0 1 2 5 6]
