<a href="https://colab.research.google.com/github/Hariom-byte/Data-Analytics-Library/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr2 =np.array([[1,2,3],[4,5,6],[7,8,9]])

print(f"Array:1{arr}")
print(f"Array:2{arr2}")
#!.shape -> no of rows and columns
print(f"the shape of the array is{arr.shape}")
print(f"the shape of the array is{arr2.shape}")

#!.ndim -> no of dimensions
print(f"the dimension of the array 1 is {arr.ndim}")
print(f"the dimension of the array 2 is {arr2.ndim}")

#!.size -> if we have to check total number of element present in your array.
print(f"the size of the array 1 is {arr.size}")
print(f"the size of the array 2 is {arr2.size}")

#!.dtype -> to check the data type
print(f"the data type of the array 1 is {arr.dtype}")
print(f"the data type of the array 2 is {arr2.dtype}")

Array:1[1 2 3 4 5]
Array:2[[1 2 3]
 [4 5 6]
 [7 8 9]]
the shape of the array is(5,)
the shape of the array is(3, 3)
the dimension of the array 1 is 1
the dimension of the array 2 is 2
the size of the array 1 is 5
the size of the array 2 is 9
the data type of the array 1 is int64
the data type of the array 2 is int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr[1]


np.int64(2)

In [ ]:
#slicing [start(0): stop: step]
arr
print(arr[1:4])

[2 3 4]


Now lets see the 2D indexing aswell

In [ ]:
matrix =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#matrix[row_index,col_index]
print(matrix[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [ ]:
print(matrix[0,2])

3


Now we can also do the slicing lets see the **slicing in 1D**

1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
print(matrix)
#matrix[row_start_index:row_stop_index], col_start_index:row_stop_index
print(matrix[0:2,0:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [ ]:
print(matrix[1:,1:])

[[5 6]
 [8 9]]


There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([5,10,15,20,25,23,16,12])
arr[arr < 18]

array([ 5, 10, 15, 16, 12])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
import numpy as np
arr = np.arange(1,11)
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])