<a href="https://colab.research.google.com/github/Hariom-byte/Data-Analytics-Library/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
pip install numpy


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

Lets create a matrix using list

In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
print(arr)
print(arr*5)

[1 2 3 4 5]
[ 5 10 15 20 25]


Now lets see how matlix looks like using numpy arrays

In [ ]:
m = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(m)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
arr = np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [ ]:
arr = np.zeros([4,4])   # no of rows and no of cols
print(arr)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr = np.ones(2)   # no of rows and no of cols
print(arr)

[1. 1.]


In [ ]:
arr = np.ones([2,2])   # no of rows and no of cols
print(arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
arr = np.full(5,7)
print(arr)

[7 7 7 7 7]


In [ ]:
arr = np.full([2,2],7)
print(arr)

[[7 7]
 [7 7]]


In [ ]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [ ]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.random.rand(3,2)  #for float
print(arr)

[[0.81712666 0.78202784]
 [0.78424076 0.67713923]
 [0.97047073 0.05538023]]


In [ ]:
arr = np.random.randint(1,100,10)   #for integers
print(arr)

[ 8 66 29 35 96 59 94 22 52 97]


In [ ]:
arr = np.random.randint(1,10,(3,3))
print(arr)

[[9 2 3]
 [2 1 1]
 [6 4 7]]


In [ ]:
arr = np.random.randn(3,3)
print(arr)
#random value that can negative value

[[-0.08487318 -1.21645804 -0.36654132]
 [ 0.78011624 -0.16210238  0.53487058]
 [-1.74545546 -0.45816019  0.82332459]]


arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution